# stages:
#     - build
#     - deploy

# cache:
#     paths: [node_modules/]


# install:
#     stage: build
#     image: node:latest
#     script: 
#         - npm install
#         - node index.js

deploy:
    image: docker:20.10.10
    stage: deploy
    services:
        - docker:20.10.10-dind
    script:
        - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker build -t registry.gitlab.com/mirfanrafif17/test-autograding:latest .
        - docker push registry.gitlab.com/mirfanrafif17/test-autograding:latest