

cache:
    paths: [node_modules/]


install:
    image: node:latest
    script: 
        - npm install
        - node index.js

deploy:
    image: 20.10.10-alpine3.14

    script:
        - docker login registry.gitlab.com
        - docker build -t registry.gitlab.com/mirfanrafif17/test-autograding .
        - docker push registry.gitlab.com/mirfanrafif17/test-autograding