name: flutter-autograding
description: "Autograding for Flutter Project"
author : Moch. Irfan Rafif
branding: 
  icon: activity
  color: purple
outputs:
  time: # id of output
    description: "Time greeting"
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: '/app/flutter-autograding/main.sh'