name: flutter-autograding
description: "Autograding for Flutter Project"
author : Moch. Irfan Rafif
branding: 
  icon: activity
  color: purple
outputs:
  time: # id of output
    description: "Time greeting"
runs:
  using: "python38"
  main: "main.py"
